export const ITEM_TIERS = Object.freeze({
  BASIC: "basic",
  MID: "mid",
  LEGENDARY: "legendary",
});

export const EQUIPMENT_IDS = Object.freeze({
  basic: Object.freeze({
    longSword: "longSword",
    dagger: "dagger",
    amplifyingTome: "amplifyingTome",
    brawlersGloves: "brawlersGloves",
    rubyCrystal: "rubyCrystal",
    sapphireCrystal: "sapphireCrystal",
    bootsOfSpeed: "bootsOfSpeed",
    clothArmor: "clothArmor",
    sheen: "sheen",
    healthPotion: "healthPotion",
    refillablePotion: "refillablePotion",
  }),
  mid: Object.freeze({
    bootsAttackSpeed: "bootsAttackSpeed",
    bootsMagic: "bootsMagic",
    bootsArmorPen: "bootsArmorPen",
    bootsCloth: "bootsCloth",
    bfSword: "bfSword",
    phage: "phage",
    noonquiver: "noonquiver",
    jingshi: "jingshi",
    caulfieldsWarhammer: "caulfieldsWarhammer",
    serratedDirk: "serratedDirk",
    vampiricScepter: "vampiricScepter",
    tiamat: "tiamat",
    recurveBow: "recurveBow",
    stinger: "stinger",
    zeal: "zeal",
    blastingWand: "blastingWand",
    needlesslyLargeRod: "needlesslyLargeRod",
    aetherWisp: "aetherWisp",
    fiendishCodex: "fiendishCodex",
    hauntingGuise: "hauntingGuise",
    hextechAlternator: "hextechAlternator",
    darkSeal: "darkSeal",
    cloakOfAgility: "cloakOfAgility",
    bamisCinder: "bamisCinder",
    giantsBelt: "giantsBelt",
    kindlegem: "kindlegem",
    lostChapter: "lostChapter",
    tearOfTheGoddess: "tearOfTheGoddess",
    chainVest: "chainVest",
    brambleVest: "brambleVest",
    wardensMail: "wardensMail",
  }),
  legendary: Object.freeze({
    brokenKingsBlade: "brokenKingsBlade",
    witsEnd: "witsEnd",
    nashorsTooth: "nashorsTooth",
    guinsosRageblade: "guinsosRageblade",
    rabadonsDeathcap: "rabadonsDeathcap",
    liandrysAnguish: "liandrysAnguish",
    infinityOrb: "infinityOrb",
    riftmaker: "riftmaker",
    soulstealerCodex: "soulstealerCodex",
    divineSunderer: "divineSunderer",
    trinityForce: "trinityForce",
    lichBane: "lichBane",
    manamune: "manamune",
    frostfireGauntlet: "frostfireGauntlet",
    infinityEdge: "infinityEdge",
    navoriQuickblades: "navoriQuickblades",
    theCollector: "theCollector",
    bloodthirster: "bloodthirster",
    runaansHurricane: "runaansHurricane",
    phantomDancer: "phantomDancer",
    frozenHeart: "frozenHeart",
    thornmail: "thornmail",
    heartsteel: "heartsteel",
    titanicHydra: "titanicHydra",
    sunfireAegis: "sunfireAegis",
    seraphsEmbrace: "seraphsEmbrace",
    bailouSword: "bailouSword",
  }),
});

const BASIC = EQUIPMENT_IDS.basic;
const MID = EQUIPMENT_IDS.mid;
const LEGENDARY = EQUIPMENT_IDS.legendary;

const makeDescription = (lines = []) =>
  lines.filter((line) => typeof line === "string" && line.trim().length > 0);

const iconPath = (folder, filename) => `assets/item/${folder}/${encodeURIComponent(filename)}`;

const RAW_ITEMS = [
  {
    key: BASIC.longSword,
    tier: ITEM_TIERS.BASIC,
    name: "长剑",
    iconFolder: "basic",
    iconFile: "长剑.png",
    cost: 500,
    stats: { attackDamageFlat: 12 },
    buildsFrom: [],
    description: ["价格：500 金币", "攻击力 +12"],
  },
  {
    key: BASIC.healthPotion,
    tier: ITEM_TIERS.BASIC,
    name: "生命药水",
    iconFolder: "consumable",
    iconFile: "healthpotion.png",
    cost: 100,
    stats: {},
    buildsFrom: [],
    effects: { healAmount: 100, autoUseThreshold: 100, consumable: true, stackable: true, maxStack: 100 },
    description: [
      "价格：100 金币",
      "主动：恢复100生命值。",
      "自动：当已损失生命值≥100时，自动使用直至<100。",
      "可叠加购买（最多100个）。",
    ],
  },
  {
    key: BASIC.refillablePotion,
    tier: ITEM_TIERS.BASIC,
    name: "复用性药水",
    iconFolder: "consumable",
    iconFile: "refillablepotion.png",
    cost: 300,
    stats: {},
    buildsFrom: [],
    effects: { healAmount: 50, autoUseThreshold: 50, consumable: true, charges: 5, refillOnStage: 5, unique: true },
    description: [
      "价格：300 金币",
      "主动：恢复50生命值，可使用5次。",
      "自动：当已损失生命值≥50时，自动使用直至<50。",
      "进入下一关卡时补充到5次。不可叠加购买。",
    ],
  },
  {
    key: BASIC.dagger,
    tier: ITEM_TIERS.BASIC,
    name: "短剑",
    iconFolder: "basic",
    iconFile: "短剑.png",
    cost: 500,
    stats: { attackSpeedPct: 0.15 },
    buildsFrom: [],
    description: ["价格：500 金币", "攻速% +15%"],
  },
  {
    key: BASIC.amplifyingTome,
    tier: ITEM_TIERS.BASIC,
    name: "增幅典籍",
    iconFolder: "basic",
    iconFile: "增幅典籍.png",
    cost: 500,
    stats: { abilityPowerFlat: 25 },
    buildsFrom: [],
    description: ["价格：500 金币", "法术强度 +25"],
  },
  {
    key: BASIC.brawlersGloves,
    tier: ITEM_TIERS.BASIC,
    name: "格斗手套",
    iconFolder: "basic",
    iconFile: "格斗手套.png",
    cost: 500,
    stats: { critChancePct: 0.10 },
    buildsFrom: [],
    description: ["价格：500 金币", "暴击率 +10%"],
  },
  {
    key: BASIC.rubyCrystal,
    tier: ITEM_TIERS.BASIC,
    name: "红水晶",
    iconFolder: "basic",
    iconFile: "红水晶.png",
    cost: 500,
    stats: { hpFlat: 150 },
    buildsFrom: [],
    description: ["价格：500 金币", "生命值 +150"],
  },
  {
    key: BASIC.sapphireCrystal,
    tier: ITEM_TIERS.BASIC,
    name: "蓝水晶",
    iconFolder: "basic",
    iconFile: "蓝水晶.png",
    cost: 500,
    stats: { manaFlat: 250 },
    buildsFrom: [],
    description: ["价格：500 金币", "法力值 +250"],
  },
  {
    key: BASIC.bootsOfSpeed,
    tier: ITEM_TIERS.BASIC,
    name: "速度之靴",
    iconFolder: "basic",
    iconFile: "速度之靴.png",
    cost: 400,
    stats: { moveSpeedFlat: 25 },
    buildsFrom: [],
    description: ["价格：400 金币", "速度 +25"],
  },
  {
    key: BASIC.clothArmor,
    tier: ITEM_TIERS.BASIC,
    name: "布甲",
    iconFolder: "basic",
    iconFile: "布甲.png",
    cost: 500,
    stats: { arFlat: 20 },
    buildsFrom: [],
    description: ["价格：500 金币", "护甲 +20"],
  },
  {
    key: BASIC.sheen,
    tier: ITEM_TIERS.BASIC,
    name: "耀光",
    iconFolder: "basic",
    iconFile: "耀光.png",
    cost: 800,
    stats: { abilityHaste: 10 },
    buildsFrom: [],
    effects: { sheenBonusBaseAdPct: 1.0 },
    description: [
      "价格：800 金币",
      "技能急速 +10",
      "被动-咏唱：施放技能后，下次普通攻击额外造成 100% 基础攻击力的物理伤害。",
    ],
  },
  {
    key: MID.bootsAttackSpeed,
    tier: ITEM_TIERS.MID,
    name: "攻速鞋",
    iconFolder: "boots",
    iconFile: "攻速鞋.png",
    cost: 1400,
    stats: { attackSpeedPct: 0.35, moveSpeedFlat: 45 },
    buildsFrom: [BASIC.bootsOfSpeed, BASIC.dagger],
    description: [
      "攻速% +35%",
      "速度 +45",
      "合成：速度之靴 + 短剑 + 500 金币",
    ],
  },
  {
    key: LEGENDARY.seraphsEmbrace,
    tier: ITEM_TIERS.LEGENDARY,
    name: "炽天使之拥",
    iconFolder: "legendary",
    iconFile: "炽天使之拥.png",
    cost: 3000,
    stats: { abilityPowerFlat: 35, abilityHaste: 20, manaFlat: 900 },
    buildsFrom: [MID.lostChapter, MID.tearOfTheGoddess],
    effects: { healPerManaSpent: 1, manaPerCast: 5, manaCapBonus: 1400 },
    description: [
      "法术强度 +35",
      "技能急速 +20",
      "法力值 +900",
      "被动：每消耗 1 点法力值，回复 1 点生命值。",
      "被动：每次释放技能提升 5 点最大法力值（最多 +1400，继承女神泪层数）。",
      "合成：遗失的章节 + 女神之泪 + 1200 金币",
    ],
  },
  {
    key: LEGENDARY.bailouSword,
    tier: ITEM_TIERS.LEGENDARY,
    name: "白楼剑",
    iconFolder: "legendary",
    iconFile: "白楼剑.png",
    cost: 3000,
    stats: { attackDamageFlat: 55, abilityHaste: 15, armorPenFlat: 15, moveSpeedPct: 0.25 },
    buildsFrom: [MID.caulfieldsWarhammer, MID.serratedDirk],
    effects: { momentumPerKill: 1, momentumSpeedPerStack: 10, momentumDurationMs: 3000, momentumMaxStacks: 10 },
    description: [
      "攻击力 +55",
      "技能急速 +15",
      "护甲穿透 +15",
      "速度 +25%",
      "被动：每击杀一名敌方单位获得 1 层动量（持续 3 秒，最多 10 层），每层提供 +10 速度。",
      "合成：考尔菲德的战锤 + 锯齿短匕 + 800 金币",
    ],
  },
  {
    key: MID.bootsMagic,
    tier: ITEM_TIERS.MID,
    name: "法穿鞋",
    iconFolder: "boots",
    iconFile: "法穿鞋.png",
    cost: 1400,
    stats: { abilityPowerFlat: 55, moveSpeedFlat: 45 },
    buildsFrom: [BASIC.bootsOfSpeed, BASIC.amplifyingTome],
    effects: { manaRegenMultiplier: 1.5 },
    description: [
      "法术强度 +55",
      "速度 +45",
      "回蓝效率 +150%",
      "合成：速度之靴 + 增幅典籍 + 500 金币",
    ],
  },
  {
    key: MID.bootsArmorPen,
    tier: ITEM_TIERS.MID,
    name: "穿甲鞋",
    iconFolder: "boots",
    iconFile: "穿甲鞋.png",
    cost: 1400,
    stats: { attackDamageFlat: 30, moveSpeedFlat: 45, armorPenFlat: 10 },
    buildsFrom: [BASIC.bootsOfSpeed, BASIC.longSword],
    description: [
      "攻击力 +30",
      "速度 +45",
      "护甲穿透 +10",
      "合成：速度之靴 + 长剑 + 500 金币",
    ],
  },
  {
    key: MID.bootsCloth,
    tier: ITEM_TIERS.MID,
    name: "布甲鞋",
    iconFolder: "boots",
    iconFile: "布甲鞋.png",
    cost: 1400,
    stats: { arFlat: 35, hpFlat: 150, moveSpeedFlat: 45 },
    buildsFrom: [BASIC.bootsOfSpeed, BASIC.clothArmor],
    effects: { hpRegenPerSecond: 10 },
    description: [
      "护甲 +35",
      "生命值 +150",
      "生命回复 +10/秒",
      "速度 +45",
      "合成：速度之靴 + 布甲 + 500 金币",
    ],
  },
  {
    key: MID.bfSword,
    tier: ITEM_TIERS.MID,
    name: "暴风大剑",
    iconFolder: "mid",
    iconFile: "暴风大剑.png",
    cost: 1500,
    stats: { attackDamageFlat: 40 },
    buildsFrom: [BASIC.longSword, BASIC.longSword],
    description: ["攻击力 +40"],
  },
  {
    key: MID.jingshi,
    tier: ITEM_TIERS.MID,
    name: "紫雨林之拳",
    iconFolder: "mid",
    iconFile: "紫雨林之拳.png",
    cost: 1200,
    stats: { attackDamageFlat: 15, hpFlat: 200 },
    buildsFrom: [BASIC.longSword, BASIC.rubyCrystal],
    description: ["攻击力 +15", "生命值 +200"],
  },
  {
    key: MID.noonquiver,
    tier: ITEM_TIERS.MID,
    name: "正午箭袋",
    iconFolder: "mid",
    iconFile: "正午箭袋.png",
    cost: 1350,
    stats: { attackDamageFlat: 25, attackSpeedPct: 0.15 },
    buildsFrom: [BASIC.longSword, BASIC.dagger],
    description: ["攻击力 +25", "攻速% +15%"],
  },
  {
    key: MID.phage,
    tier: ITEM_TIERS.MID,
    name: "净蚀",
    iconFolder: "mid",
    iconFile: "净蚀.png",
    cost: 1000,
    stats: { attackDamageFlat: 15, hpFlat: 150 },
    buildsFrom: [BASIC.longSword],
    effects: { phageSpeedBonus: 20, phageDurationMs: 2000 },
    description: [
      "攻击力 +15",
      "生命值 +150",
      "被动：普攻命中提供 20 速度，持续 2 秒。",
    ],
  },
  {
    key: MID.caulfieldsWarhammer,
    tier: ITEM_TIERS.MID,
    name: "考尔菲德的战锤",
    iconFolder: "mid",
    iconFile: "考尔菲德的战锤.png",
    cost: 1500,
    stats: { attackDamageFlat: 25, abilityHaste: 10 },
    buildsFrom: [BASIC.longSword, BASIC.longSword],
    description: ["攻击力 +25", "技能急速 +10"],
  },
  {
    key: MID.serratedDirk,
    tier: ITEM_TIERS.MID,
    name: "锯齿短匕",
    iconFolder: "mid",
    iconFile: "锯齿短匕.png",
    cost: 1000,
    stats: { attackDamageFlat: 20, armorPenFlat: 8 },
    buildsFrom: [BASIC.longSword],
    description: ["攻击力 +20", "护甲穿透 +8"],
  },
  {
    key: MID.vampiricScepter,
    tier: ITEM_TIERS.MID,
    name: "吸血鬼节杖",
    iconFolder: "mid",
    iconFile: "吸血鬼节杖.png",
    cost: 1200,
    stats: { attackDamageFlat: 20, physicalLifeSteal: 0.08 },
    buildsFrom: [BASIC.longSword],
    description: ["攻击力 +20", "物理吸血 +8%"],
  },
  {
    key: MID.tiamat,
    tier: ITEM_TIERS.MID,
    name: "提亚马特",
    iconFolder: "mid",
    iconFile: "提亚马特.png",
    cost: 1200,
    stats: { attackDamageFlat: 25 },
    buildsFrom: [BASIC.longSword, BASIC.longSword],
    effects: { cleaveFlat: 30 },
    description: [
      "攻击力 +25",
      "被动：范围伤害与普攻伤害无关，固定造成 30 点伤害（远程半径 2 格，近战半径 3 格）。",
    ],
  },
  {
    key: MID.recurveBow,
    tier: ITEM_TIERS.MID,
    name: "反曲弓",
    iconFolder: "mid",
    iconFile: "反曲弓.png",
    cost: 1400,
    stats: { attackSpeedPct: 0.30 },
    buildsFrom: [BASIC.dagger, BASIC.dagger],
    effects: { onHitPhysicalFlat: 15 },
    description: ["攻速% +30%", "被动：普攻附带 15 点物理特效伤害。"],
  },
  {
    key: MID.stinger,
    tier: ITEM_TIERS.MID,
    name: "蜂刺",
    iconFolder: "mid",
    iconFile: "蜂刺.png",
    cost: 1200,
    stats: { attackSpeedPct: 0.30, abilityHaste: 10 },
    buildsFrom: [BASIC.dagger],
    description: ["攻速% +30%", "技能急速 +10"],
  },
  {
    key: MID.zeal,
    tier: ITEM_TIERS.MID,
    name: "狂热",
    iconFolder: "mid",
    iconFile: "狂热.png",
    cost: 1400,
    stats: { attackSpeedPct: 0.15, critChancePct: 0.15, moveSpeedPct: 0.05 },
    buildsFrom: [BASIC.dagger, BASIC.brawlersGloves],
    description: [
      "攻速% +15%",
      "暴击率 +15%",
      "速度 +5%",
    ],
  },
  {
    key: MID.blastingWand,
    tier: ITEM_TIERS.MID,
    name: "爆裂魔杖",
    iconFolder: "mid",
    iconFile: "爆裂魔杖.png",
    cost: 800,
    stats: { abilityPowerFlat: 40 },
    buildsFrom: [BASIC.amplifyingTome],
    description: ["法术强度 +40"],
  },
  {
    key: MID.needlesslyLargeRod,
    tier: ITEM_TIERS.MID,
    name: "无用大棒",
    iconFolder: "mid",
    iconFile: "无用大棒.png",
    cost: 1500,
    stats: { abilityPowerFlat: 60 },
    buildsFrom: [BASIC.amplifyingTome, BASIC.amplifyingTome],
    description: ["法术强度 +60"],
  },
  {
    key: MID.aetherWisp,
    tier: ITEM_TIERS.MID,
    name: "以太精魂",
    iconFolder: "mid",
    iconFile: "以太精魂.png",
    cost: 950,
    stats: { abilityPowerFlat: 35, moveSpeedPct: 0.05 },
    buildsFrom: [BASIC.amplifyingTome],
    description: ["法术强度 +35", "速度 +5%"],
  },
  {
    key: MID.fiendishCodex,
    tier: ITEM_TIERS.MID,
    name: "恶魔法典",
    iconFolder: "mid",
    iconFile: "恶魔法典.png",
    cost: 1000,
    stats: { abilityPowerFlat: 35, abilityHaste: 10 },
    buildsFrom: [BASIC.amplifyingTome],
    description: ["法术强度 +35", "技能急速 +10"],
  },
  {
    key: MID.hauntingGuise,
    tier: ITEM_TIERS.MID,
    name: "幽魂面具",
    iconFolder: "mid",
    iconFile: "幽魂面具.png",
    cost: 900,
    stats: { abilityPowerFlat: 30, hpFlat: 100 },
    buildsFrom: [BASIC.amplifyingTome],
    description: ["法术强度 +30", "生命值 +100"],
  },
  {
    key: MID.hextechAlternator,
    tier: ITEM_TIERS.MID,
    name: "海克斯发电机",
    iconFolder: "mid",
    iconFile: "海克斯发电机.png",
    cost: 1400,
    stats: { abilityPowerFlat: 25, hpFlat: 150 },
    buildsFrom: [BASIC.amplifyingTome, BASIC.rubyCrystal],
    effects: { onHitMagicFlat: 25 },
    description: [
      "法术强度 +25",
      "生命值 +150",
      "被动：技能与强化普攻额外造成 25 点魔法伤害。",
    ],
  },
  {
    key: MID.darkSeal,
    tier: ITEM_TIERS.MID,
    name: "杀人书",
    iconFolder: "mid",
    iconFile: "杀人书.png",
    cost: 1800,
    stats: { abilityPowerFlat: 25, hpFlat: 70, manaFlat: 200 },
    buildsFrom: [BASIC.amplifyingTome],
    effects: {
      stackApPerKill: 5,
      maxStacks: 30,
      msBonusThreshold: 10,
      msBonusPct: 0.10,
      killsPerStack: 100,
      bossStackBonus: 1,
    },
    description: [
      "法术强度 +25",
      "生命值 +70",
      "法力值 +200",
      "被动：击杀 100 个小兵或 1 个 Boss 获得 1 层荣耀（最多 30 层），每层提供 5 法术强度；至少 10 层时获得速度 +10%。",
    ],
  },
  {
    key: MID.cloakOfAgility,
    tier: ITEM_TIERS.MID,
    name: "灵巧披风",
    iconFolder: "mid",
    iconFile: "灵巧披风.png",
    cost: 1000,
    stats: { critChancePct: 0.20 },
    buildsFrom: [BASIC.brawlersGloves],
    description: ["暴击率 +20%"],
  },
  {
    key: MID.bamisCinder,
    tier: ITEM_TIERS.MID,
    name: "熔渣",
    iconFolder: "mid",
    iconFile: "熔渣.png",
    cost: 1300,
    stats: { hpFlat: 300 },
    buildsFrom: [BASIC.rubyCrystal, BASIC.rubyCrystal],
    effects: { auraDamage: 20, auraIntervalMs: 500, auraRadius: 25 },
    description: [
      "生命值 +300",
      "被动：每 0.5 秒对半径 25 内的敌人造成 20 点魔法伤害。",
    ],
  },
  {
    key: MID.giantsBelt,
    tier: ITEM_TIERS.MID,
    name: "巨人腰带",
    iconFolder: "mid",
    iconFile: "巨人腰带.png",
    cost: 1000,
    stats: { hpFlat: 300 },
    buildsFrom: [BASIC.rubyCrystal],
    description: ["生命值 +300"],
  },
  {
    key: MID.kindlegem,
    tier: ITEM_TIERS.MID,
    name: "燃烧宝石",
    iconFolder: "mid",
    iconFile: "燃烧宝石.png",
    cost: 1000,
    stats: { hpFlat: 200, abilityHaste: 10 },
    buildsFrom: [BASIC.rubyCrystal],
    description: ["生命值 +200", "技能急速 +10"],
  },
  {
    key: MID.lostChapter,
    tier: ITEM_TIERS.MID,
    name: "遗失的章节",
    iconFolder: "mid",
    iconFile: "遗失的章节.png",
    cost: 900,
    stats: { abilityPowerFlat: 30, manaFlat: 300 },
    buildsFrom: [BASIC.sapphireCrystal],
    effects: { manaRegenPerSecond: 10 },
    description: [
      "法术强度 +30",
      "法力值 +300",
      "被动：每秒回复 10 点法力值。",
    ],
  },
  {
    key: MID.tearOfTheGoddess,
    tier: ITEM_TIERS.MID,
    name: "女神之泪",
    iconFolder: "mid",
    iconFile: "女神之泪.png",
    cost: 900,
    stats: { manaFlat: 500, abilityHaste: 10 },
    buildsFrom: [BASIC.sapphireCrystal],
    effects: { manaPerCast: 5, manaCapBonus: 700 },
    description: [
      "法力值 +500",
      "技能急速 +10",
      "被动：每次释放技能提升 5 点最大法力值（最多 +700）。",
    ],
  },
  {
    key: MID.chainVest,
    tier: ITEM_TIERS.MID,
    name: "锁子甲",
    iconFolder: "mid",
    iconFile: "锁子甲.png",
    cost: 900,
    stats: { arFlat: 40 },
    buildsFrom: [BASIC.clothArmor],
    description: ["护甲 +40"],
  },
  {
    key: MID.brambleVest,
    tier: ITEM_TIERS.MID,
    name: "父亲背心",
    iconFolder: "mid",
    iconFile: "父亲背心.png",
    cost: 1000,
    stats: { arFlat: 30 },
    buildsFrom: [BASIC.clothArmor],
    effects: { thornsBase: 4, thornsArmorRatio: 0.10 },
    description: [
      "护甲 +30",
      "被动：受到攻击时，对攻击者造成 4 + 10% 护甲的魔法伤害。",
    ],
  },
  {
    key: MID.wardensMail,
    tier: ITEM_TIERS.MID,
    name: "爷爷铠甲",
    iconFolder: "mid",
    iconFile: "爷爷铠甲.png",
    cost: 1050,
    stats: { arFlat: 35, defFlat: 10 },
    buildsFrom: [BASIC.clothArmor, BASIC.clothArmor],
    description: ["护甲 +35", "防御 +10"],
  },
  {
    key: LEGENDARY.brokenKingsBlade,
    tier: ITEM_TIERS.LEGENDARY,
    name: "破败王者之刃",
    iconFolder: "legendary",
    iconFile: "破败王者之刃.png",
    cost: 3200,
    stats: { attackDamageFlat: 25, attackSpeedPct: 0.35, physicalLifeSteal: 0.10 },
    buildsFrom: [MID.vampiricScepter, MID.recurveBow],
    effects: {
      percentCurrentHp: 0.07,
      percentMinDamage: 15,
      percentMaxDamageNonBoss: 60,
      percentMaxDamageBoss: 300,
      tripleHitThreshold: 3,
      tripleHitWindowMs: 2000,
      tripleHitMagicDamage: 30,
      tripleHitSlowPct: 0.25,
      tripleHitSlowMs: 2000,
      selfHastePct: 0.25,
      selfHasteMs: 2000,
    },
    description: [
      "攻击力 +25",
      "攻速% +35%",
      "物理吸血 +10%",
      "被动-渴血：普攻附带目标当前生命值 7% 的物理特效伤害（至少 15 点，对非 Boss 至多 60 点，对 Boss 至多 300 点）。",
      "被动-汲取：2 秒内连续 3 次命中同一敌人时，额外造成 30 魔法伤害并使其减速 25% 持续 2 秒，同时自身获得 25% 速度加成，持续 2 秒。",
    ],
  },
  {
    key: LEGENDARY.witsEnd,
    tier: ITEM_TIERS.LEGENDARY,
    name: "智慧末刃",
    iconFolder: "legendary",
    iconFile: "智慧末刃.png",
    cost: 2800,
    stats: { arFlat: 45, attackSpeedPct: 0.45 },
    buildsFrom: [MID.recurveBow, MID.chainVest],
    effects: {
      witsMagicOnHit: 30,
      witsHealThresholdHpPct: 0.5,
      witsHealPctOfOnHit: 1.0,
    },
    description: [
      "护甲 +45",
      "攻速% +45%",
      "被动：普攻附带 30 点魔法特效伤害；当生命值低于 50% 时，回复与特效伤害等量的生命值。",
    ],
  },
  {
    key: LEGENDARY.nashorsTooth,
    tier: ITEM_TIERS.LEGENDARY,
    name: "纳什之牙",
    iconFolder: "legendary",
    iconFile: "纳什之牙.png",
    cost: 3000,
    stats: { abilityHaste: 20, attackSpeedPct: 0.45, abilityPowerFlat: 50 },
    buildsFrom: [MID.recurveBow, MID.blastingWand],
    effects: {
      nashorBase: 15,
      nashorBonusAdRatio: 0.25,
      nashorApRatio: 0.25,
    },
    description: [
      "技能急速 +20",
      "攻速% +45%",
      "法术强度 +50",
      "被动：普攻命中造成 15 + 25% 额外攻击力 + 25% 法术强度的魔法特效伤害。",
    ],
  },
  {
    key: LEGENDARY.guinsosRageblade,
    tier: ITEM_TIERS.LEGENDARY,
    name: "鬼索的狂暴之刃",
    iconFolder: "legendary",
    iconFile: "鬼索的狂暴之刃.png",
    cost: 3000,
    stats: { attackDamageFlat: 35, abilityPowerFlat: 35, attackSpeedPct: 0.25 },
    buildsFrom: [BASIC.amplifyingTome, BASIC.longSword, MID.recurveBow],
    effects: {
      ragebladeMagicOnHit: 30,
      ragebladeStackAsPct: 0.08,
      ragebladeMaxStacks: 4,
      ragebladeStackDurationMs: 5000,
      ragebladeExtraProcsAtFull: 2,
      ragebladeExtraProcEvery: 3,
    },
    description: [
      "攻击力 +35",
      "法术强度 +35",
      "攻速% +25%",
      "被动-怨怒：普攻附带 30 点魔法特效伤害。",
      "被动-沸腾打击：普攻提供 8% 攻速加成，最多 4 层；满层时每第 3 次普攻额外触发 2 次特效。",
    ],
  },
  {
    key: LEGENDARY.rabadonsDeathcap,
    tier: ITEM_TIERS.LEGENDARY,
    name: "灭世者的死亡之帽",
    iconFolder: "legendary",
    iconFile: "灭世者的死亡之帽.png",
    cost: 4000,
    stats: { abilityPowerFlat: 120 },
    buildsFrom: [MID.needlesslyLargeRod, MID.needlesslyLargeRod],
    effects: { apMultiplier: 0.5 },
    description: [
      "法术强度 +120",
      "被动：总法术强度提升 25%。",
    ],
  },
  {
    key: LEGENDARY.liandrysAnguish,
    tier: ITEM_TIERS.LEGENDARY,
    name: "兰德里的折磨",
    iconFolder: "legendary",
    iconFile: "兰德里的折磨.png",
    cost: 3000,
    stats: { abilityPowerFlat: 75, hpFlat: 300 },
    buildsFrom: [MID.blastingWand, MID.hauntingGuise, BASIC.rubyCrystal],
    effects: { burnDurationMs: 3000, burnPercentBasePerSecond: 0.01, burnPercentApRatio: 0.0001 },
    description: [
      "法术强度 +75",
      "生命值 +300",
      "被动：技能灼烧目标 3 秒，每秒造成其最大生命值 1% + (法术强度 × 0.01%) 的魔法伤害。",
    ],
  },
  {
    key: LEGENDARY.infinityOrb,
    tier: ITEM_TIERS.LEGENDARY,
    name: "无限法球",
    iconFolder: "legendary",
    iconFile: "无限法球.png",
    cost: 3450,
    stats: { abilityPowerFlat: 85 },
    buildsFrom: [MID.aetherWisp, MID.needlesslyLargeRod],
    effects: { executeHpPct: 0.5, magicCritMultiplier: 1.5 },
    description: [
      "法术强度 +85",
      "被动：对生命值低于 50% 的敌人造成暴击（150% 伤害）。",
    ],
  },
  {
    key: LEGENDARY.riftmaker,
    tier: ITEM_TIERS.LEGENDARY,
    name: "峡谷制造者",
    iconFolder: "legendary",
    iconFile: "峡谷制造者.png",
    cost: 3100,
    stats: { abilityPowerFlat: 80, abilityHaste: 15, hpFlat: 350 },
    buildsFrom: [MID.hauntingGuise, MID.hextechAlternator],
    effects: { onHitMagicFlat: 25, apFromHpPct: 0.05, omniVampPct: 0.10 },
    description: [
      "法术强度 +80",
      "技能急速 +15",
      "生命值 +350",
      "全能吸血 +10%",
      "被动：技能与普攻额外造成 25 点魔法伤害，并获得等同于 5% 生命值的法术强度。",
    ],
  },
  {
    key: LEGENDARY.soulstealerCodex,
    tier: ITEM_TIERS.LEGENDARY,
    name: "窃魂法典",
    iconFolder: "legendary",
    iconFile: "窃魂法典.png",
    cost: 3000,
    stats: { abilityPowerFlat: 65, abilityHaste: 20, hpFlat: 200 },
    buildsFrom: [MID.fiendishCodex, MID.hextechAlternator],
    effects: { killCooldownRefundPct: 0.25 },
    description: [
      "法术强度 +65",
      "技能急速 +20",
      "生命值 +200",
      "被动：击杀单位立刻返还当前技能冷却时间的 25%。",
    ],
  },
  {
    key: LEGENDARY.divineSunderer,
    tier: ITEM_TIERS.LEGENDARY,
    name: "神圣分离者",
    iconFolder: "legendary",
    iconFile: "神圣分离者.png",
    cost: 3400,
    stats: { attackDamageFlat: 25, abilityHaste: 25, hpFlat: 500 },
    buildsFrom: [BASIC.sheen, MID.phage, MID.kindlegem],
    effects: { spellbladeBaseAdPct: 1.0, spellbladeMaxHpPct: 0.05, spellbladeMaxDamageBoss: 800, spellbladeDamageType: "physical" },
    description: [
      "攻击力 +25",
      "技能急速 +25",
      "生命值 +500",
      "被动：施放技能后，下次普攻额外造成 100% 基础攻击力 + 敌人最大生命值 5% 的物理伤害（对 Boss 至多 800）。",
    ],
  },
  {
    key: LEGENDARY.trinityForce,
    tier: ITEM_TIERS.LEGENDARY,
    name: "三相之力",
    iconFolder: "legendary",
    iconFile: "三相之力.png",
    cost: 3333,
    stats: { attackDamageFlat: 30, abilityHaste: 25, attackSpeedPct: 0.30, hpFlat: 250 },
    buildsFrom: [BASIC.sheen, MID.jingshi, MID.stinger],
    effects: { spellbladeBaseAdPct: 3.0, spellbladeMoveSpeed: 100, spellbladeMoveSpeedDurationMs: 2000, spellbladeDamageType: "physical" },
    description: [
      "攻击力 +30",
      "技能急速 +25",
      "攻速% +30%",
      "生命值 +250",
      "被动：施放技能后，下次普攻额外造成 300% 基础攻击力的物理伤害，并获得 100 速度，持续 2 秒。",
    ],
  },
  {
    key: LEGENDARY.lichBane,
    tier: ITEM_TIERS.LEGENDARY,
    name: "巫妖之祸",
    iconFolder: "legendary",
    iconFile: "巫妖之祸.png",
    cost: 2950,
    stats: { abilityPowerFlat: 80, abilityHaste: 10 },
    buildsFrom: [MID.aetherWisp, BASIC.amplifyingTome, BASIC.sheen],
    effects: { spellbladeAdRatio: 1.0, spellbladeApRatio: 1.0, spellbladeDamageType: "magic" },
    description: [
      "法术强度 +80",
      "技能急速 +10",
      "被动：施放技能后，下次普攻额外造成 100% 攻击力 + 100% 法术强度的魔法伤害。",
    ],
  },
  {
    key: LEGENDARY.manamune,
    tier: ITEM_TIERS.LEGENDARY,
    name: "吸蓝刀",
    iconFolder: "legendary",
    iconFile: "吸蓝刀.png",
    cost: 3000,
    stats: { attackDamageFlat: 35, abilityHaste: 20, critChancePct: 0.25 },
    buildsFrom: [MID.cloakOfAgility, BASIC.longSword, BASIC.sheen],
    effects: { spellbladeBaseAdPct: 0.7, spellbladeCanCrit: true, onHitMissingManaRestorePct: 0.03, spellbladeDamageType: "physical" },
    description: [
      "攻击力 +35",
      "技能急速 +20",
      "暴击率 +25%",
      "被动：施放技能后，下次普攻额外造成 70% 基础攻击力的物理伤害，可暴击；普攻额外回复 3% 已损失法力值。",
    ],
  },
  {
    key: LEGENDARY.frostfireGauntlet,
    tier: ITEM_TIERS.LEGENDARY,
    name: "冰拳",
    iconFolder: "legendary",
    iconFile: "冰拳.png",
    cost: 3100,
    stats: { abilityHaste: 30, arFlat: 50, defFlat: 20, hpFlat: 250 },
    buildsFrom: [MID.wardensMail, MID.kindlegem, BASIC.sheen],
    effects: {
      spellbladeAdRatio: 1.0,
      spellbladeArmorRatio: 1.0,
      spellbladeDamageType: "physical",
      frostSlowPct: 0.5,
      frostSlowRadiusBase: 100,
      frostSlowRadiusArmorRatio: 0.10,
    },
    description: [
      "技能急速 +30",
      "护甲 +50",
      "防御 +20",
      "生命值 +250",
      "被动：施放技能后，下次普攻额外造成 100% 攻击力 + 100% 护甲的物理伤害，并在半径 (100 + 护甲 ×10%) 内减速敌人 25%。",
    ],
  },
  {
    key: LEGENDARY.infinityEdge,
    tier: ITEM_TIERS.LEGENDARY,
    name: "无尽之刃",
    iconFolder: "legendary",
    iconFile: "无尽之刃.png",
    cost: 3400,
    stats: { attackDamageFlat: 60, critChancePct: 0.25, critDamageBonusPct: 0.5 },
    buildsFrom: [MID.bfSword, MID.cloakOfAgility],
    description: ["攻击力 +60", "暴击率 +25%", "暴击伤害% +50%"],
  },
  {
    key: LEGENDARY.navoriQuickblades,
    tier: ITEM_TIERS.LEGENDARY,
    name: "讯刃",
    iconFolder: "legendary",
    iconFile: "讯刃.png",
    cost: 3000,
    stats: { attackDamageFlat: 40, attackSpeedPct: 0.35, critChancePct: 0.25 },
    buildsFrom: [MID.cloakOfAgility, MID.noonquiver],
    effects: { cooldownRefundOnHitPct: 0.15 },
    description: [
      "攻击力 +40",
      "攻速% +35%",
      "暴击率 +25%",
      "被动：普攻命中时减少当前技能总冷却时间 15%。",
    ],
  },
  {
    key: LEGENDARY.theCollector,
    tier: ITEM_TIERS.LEGENDARY,
    name: "收集者",
    iconFolder: "legendary",
    iconFile: "收集者.png",
    cost: 2900,
    stats: { attackDamageFlat: 45, critChancePct: 0.25, armorPenFlat: 10 },
    buildsFrom: [MID.cloakOfAgility, MID.serratedDirk],
    effects: { executeThresholdPct: 0.05, executeBonusGold: 25 },
    description: [
      "攻击力 +45",
      "暴击率 +25%",
      "护甲穿透 +10",
      "被动：处决生命值低于 5% 的敌人并额外掉落 25 金币。",
    ],
  },
  {
    key: LEGENDARY.bloodthirster,
    tier: ITEM_TIERS.LEGENDARY,
    name: "饮血剑",
    iconFolder: "legendary",
    iconFile: "饮血剑.png",
    cost: 3100,
    stats: { attackDamageFlat: 70, attackSpeedPct: 0.15, critChancePct: 0.25, physicalLifeSteal: 0.25 },
    buildsFrom: [MID.cloakOfAgility, MID.vampiricScepter],
    description: [
      "攻击力 +70",
      "攻速% +15%",
      "暴击率 +25%",
      "物理吸血 +25%",
    ],
  },
  {
    key: LEGENDARY.runaansHurricane,
    tier: ITEM_TIERS.LEGENDARY,
    name: "卢安娜的飓风",
    iconFolder: "legendary",
    iconFile: "卢安娜的飓风.png",
    cost: 3100,
    stats: { attackSpeedPct: 0.50, critChancePct: 0.25 },
    buildsFrom: [MID.zeal, MID.recurveBow],
    effects: { boltCount: 2, boltDamageMultiplier: 0.55, boltsTriggerOnHit: true },
    description: [
      "攻速% +50%",
      "暴击率 +25%",
      "被动：普攻额外朝附近最多 2 个敌人发射弩箭，造成 55% 攻击力的物理伤害，可触发特效与暴击。",
    ],
  },
  {
    key: LEGENDARY.phantomDancer,
    tier: ITEM_TIERS.LEGENDARY,
    name: "幻影之舞",
    iconFolder: "legendary",
    iconFile: "幻影之舞.png",
    cost: 3100,
    stats: { attackSpeedPct: 0.60, critChancePct: 0.25, moveSpeedPct: 0.10 },
    buildsFrom: [MID.zeal, MID.recurveBow],
    effects: { phaseThroughEnemies: true },
    description: [
      "攻速% +60%",
      "暴击率 +25%",
      "速度 +10%",
      "被动：可以穿过敌人单位。",
    ],
  },
  {
    key: LEGENDARY.frozenHeart,
    tier: ITEM_TIERS.LEGENDARY,
    name: "蓝盾",
    iconFolder: "legendary",
    iconFile: "蓝盾.png",
    cost: 3000,
    stats: { arFlat: 75, defFlat: 50, hpFlat: 400 },
    buildsFrom: [MID.wardensMail, MID.giantsBelt],
    description: [
      "护甲 +75",
      "防御 +50",
      "生命值 +400",
    ],
  },
  {
    key: LEGENDARY.thornmail,
    tier: ITEM_TIERS.LEGENDARY,
    name: "反甲",
    iconFolder: "legendary",
    iconFile: "反甲.png",
    cost: 2700,
    stats: { arFlat: 100 },
    buildsFrom: [MID.brambleVest, MID.chainVest],
    effects: { thornsBase: 10, thornsArmorRatio: 0.20 },
    description: [
      "护甲 +100",
      "被动：受到攻击时，反弹 10 + 20% 护甲的魔法伤害。",
    ],
  },
  {
    key: LEGENDARY.heartsteel,
    tier: ITEM_TIERS.LEGENDARY,
    name: "心之钢",
    iconFolder: "legendary",
    iconFile: "心之钢.png",
    cost: 3000,
    stats: { hpFlat: 1000 },
    buildsFrom: [MID.giantsBelt, MID.giantsBelt],
    effects: { maxHpPerKill: 1 },
    description: [
      "生命值 +1000",
      "被动：击杀任意单位永久提升 1 点最大生命值。",
    ],
  },
  {
    key: LEGENDARY.titanicHydra,
    tier: ITEM_TIERS.LEGENDARY,
    name: "巨型九头蛇",
    iconFolder: "legendary",
    iconFile: "巨型九头蛇.png",
    cost: 3000,
    stats: { attackDamageFlat: 25, hpFlat: 500 },
    buildsFrom: [MID.giantsBelt, MID.tiamat],
    effects: { cleavePercentMaxHp: 0.08, cleaveFlat: 30 },
    description: [
      "攻击力 +25",
      "生命值 +500",
      "被动：普攻额外造成 30 + 自身最大生命值 8% 的范围伤害（远程半径 2.5 格，近战半径 4 格）。",
    ],
  },
  {
    key: LEGENDARY.sunfireAegis,
    tier: ITEM_TIERS.LEGENDARY,
    name: "日炎圣盾",
    iconFolder: "legendary",
    iconFile: "日炎圣盾.png",
    cost: 2900,
    stats: { hpFlat: 500, abilityHaste: 15 },
    buildsFrom: [MID.bamisCinder, MID.kindlegem],
    effects: { auraDamage: 30, auraDamageHpRatio: 0.008, auraIntervalMs: 500, auraRadius: 50 },
    description: [
      "生命值 +500",
      "技能急速 +15",
      "被动：每 0.5 秒对半径 50 内的敌人造成 30 + 0.8% 最大生命值的魔法伤害。",
    ],
  },
];

export const EQUIPMENT_DATA = (() => {
  const data = {};

  RAW_ITEMS.forEach((item) => {
    data[item.key] = {
      id: item.key,
      tier: item.tier,
      name: item.name,
      icon: iconPath(item.iconFolder, item.iconFile),
      cost: item.cost,
      stats: item.stats ? { ...item.stats } : {},
      buildsFrom: item.buildsFrom ? [...item.buildsFrom] : [],
      effects: item.effects ? { ...item.effects } : undefined,
      description: makeDescription(item.description),
      textureKey: item.textureKey ?? `item_${item.key}`,
    };
  });

  Object.values(data).forEach((item) => {
    const componentCost = item.buildsFrom.reduce(
      (sum, compId) => sum + (data[compId]?.cost ?? 0),
      0,
    );
    item.combineCost = Math.max(0, item.cost - componentCost);
  });

  Object.values(data).forEach((item) => {
    item.buildsFrom.forEach((componentId) => {
      const component = data[componentId];
      if (!component) return;
      if (!component.buildsInto) component.buildsInto = [];
      if (!component.buildsInto.includes(item.id)) component.buildsInto.push(item.id);
    });
  });

  Object.values(data).forEach((item) => {
    item.sellPrice = Math.floor(item.cost * 0.7);
  });

  return data;
})();



